/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Adrián Ortiz
 */
public class ListaClientes extends javax.swing.JFrame {

    /**
     * Creates new form ListaClientes
     */
    public ListaClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        jspTablaClientes = new javax.swing.JScrollPane();
        tblListaClientes = new javax.swing.JTable();
        ListaClientes = new javax.swing.JLabel();
        btnSalir1 = new javax.swing.JButton();
        jspTablaClientes1 = new javax.swing.JScrollPane();
        tblListaClientes1 = new javax.swing.JTable();
        ListaClientes1 = new javax.swing.JLabel();

        btnSalir.setText("SALIR");

        tblListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre(s)", "Apellidos", "Teléfono", "Fecha de nacimiento"
            }
        ));
        jspTablaClientes.setViewportView(tblListaClientes);

        ListaClientes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ListaClientes.setText("LISTA DE CLIENTES");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSalir1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSalir1.setText("SALIR");

        tblListaClientes1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblListaClientes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"scas", "casc", " c cvx", "dsv"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre(s)", "Apellidos", "Teléfono", "Fecha de nacimiento"
            }
        ));
        jspTablaClientes1.setViewportView(tblListaClientes1);

        ListaClientes1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        ListaClientes1.setText("LISTA DE CLIENTES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ListaClientes1)
                        .addComponent(jspTablaClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 1652, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(ListaClientes1)
                .addGap(18, 18, 18)
                .addComponent(jspTablaClientes1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir1)
                .addGap(120, 120, 120))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaClientes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ListaClientes;
    private javax.swing.JLabel ListaClientes1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JScrollPane jspTablaClientes;
    private javax.swing.JScrollPane jspTablaClientes1;
    private javax.swing.JTable tblListaClientes;
    private javax.swing.JTable tblListaClientes1;
    // End of variables declaration//GEN-END:variables
}
