/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Codigo.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.misc.Compare;

/**
 *
 * @author Adrián Ortiz
 */
public class RegistroClientes extends javax.swing.JFrame {
    
    Conexion cc=new Conexion();
    Connection con= cc.conexion();
    /**
     * Creates new form RegistroClientes
     */
    public RegistroClientes() {
        initComponents();
        llenarTabla();
    }
    
    private int privileges;

    public int getPrivileges() {
        return privileges;
    }

    public void setPrivileges(int privileges) {
        this.privileges = privileges;
    }
    public void llenarTabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        ResultSet res = null;
        try {
            String SQL="call mostrarEmpleados()";
            PreparedStatement pst= con.prepareStatement(SQL);
            res= pst.executeQuery();
            modelo.setColumnIdentifiers(new Object[]{"Nombres","Apellidos", "Calle y Numero", "Colonia", "NSS", "RFC","Fecha del Contrato","Telefono","Correo"});
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
        }
        try {
            while (res.next()){
                modelo.addRow(new Object[]{res.getString("nombreEmp"), res.getString("apellidosEmp"), res.getString("calleNumeroEmp"), res.getString("Colonia"), res.getString("NSSEmp"), res.getString("RFCEmp"), res.getString("fechaContrato"), res.getString("telefonoEmp"), res.getString("correoEmp")});
            }
            tblEmpleados.setModel(modelo);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Nombres = new javax.swing.JLabel();
        CalleyNumero = new javax.swing.JLabel();
        NumTel = new javax.swing.JLabel();
        Apellidos = new javax.swing.JLabel();
        Colonia = new javax.swing.JLabel();
        tfNombres = new javax.swing.JTextField();
        tfNumTel = new javax.swing.JTextField();
        tfCalleYNumero = new javax.swing.JTextField();
        tfApellidos = new javax.swing.JTextField();
        tfColonia = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        FechaNac = new javax.swing.JLabel();
        tfDia = new javax.swing.JTextField();
        tfMes = new javax.swing.JTextField();
        tfAnio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        imgLogo3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(722, 628));
        setMinimumSize(new java.awt.Dimension(722, 628));
        setPreferredSize(new java.awt.Dimension(722, 638));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Nombres.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Nombres.setText("NOMBRE(S):");

        CalleyNumero.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CalleyNumero.setText("CALLE Y NÚMERO:");

        NumTel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        NumTel.setText("TELEFONO:");

        Apellidos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Apellidos.setText("APELLIDOS:");

        Colonia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Colonia.setText("COLONIA:");

        tfNombres.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tfNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombresActionPerformed(evt);
            }
        });
        tfNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombresKeyTyped(evt);
            }
        });

        tfNumTel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tfNumTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNumTelKeyTyped(evt);
            }
        });

        tfCalleYNumero.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        tfApellidos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tfApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApellidosActionPerformed(evt);
            }
        });
        tfApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfApellidosKeyTyped(evt);
            }
        });

        tfColonia.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tfColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfColoniaActionPerformed(evt);
            }
        });
        tfColonia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfColoniaKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfColoniaKeyReleased(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAlta.setBackground(new java.awt.Color(51, 204, 0));
        btnAlta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAlta.setForeground(new java.awt.Color(255, 255, 255));
        btnAlta.setText("REGISTRAR");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        FechaNac.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        FechaNac.setText("FECHA DE NACIMIENTO");

        tfDia.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tfDia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDia.setText("DD");
        tfDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDiaActionPerformed(evt);
            }
        });

        tfMes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tfMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfMes.setText("MM");
        tfMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMesActionPerformed(evt);
            }
        });

        tfAnio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tfAnio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfAnio.setText("AAAA");
        tfAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("/");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("/");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Nombres, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNombres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(Colonia, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfColonia, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(NumTel)
                    .addComponent(tfNumTel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CalleyNumero)
                    .addComponent(FechaNac)
                    .addComponent(tfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellidos)
                    .addComponent(tfCalleYNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfDia, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tfMes, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tfAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(107, 107, 107))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombres)
                    .addComponent(Apellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(tfApellidos))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumTel)
                            .addComponent(FechaNac))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfAnio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNumTel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMes)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 1, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addComponent(tfDia)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Colonia)
                    .addComponent(CalleyNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCalleYNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlta)
                    .addComponent(btnCancelar))
                .addGap(35, 35, 35))
        );

        jPanel6.setBackground(new java.awt.Color(164, 55, 123));

        imgLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/LogoChico.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FORMULARIO DE CLIENTE");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(imgLogo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(1225, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(imgLogo3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre(s)", "Apellidos", "Telefono", "Calle y numero", "Colonia", "NSS", "RFC"
            }
        ));
        jScrollPane1.setViewportView(tblEmpleados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(674, 674, 674)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(494, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(149, 149, 149)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(183, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombresActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        if(tfNombres.getText().compareToIgnoreCase("")==0 || tfApellidos.getText().compareToIgnoreCase("")==0 || tfNumTel.getText().compareToIgnoreCase("")==0 || tfCalleYNumero.getText().compareToIgnoreCase("")==0 || tfColonia.getText().compareToIgnoreCase("")==0 || tfDia.getText().compareToIgnoreCase("")==0 || tfMes.getText().compareToIgnoreCase("")==0 || tfAnio.getText().compareToIgnoreCase("")==0 || tfDia.getText().compareToIgnoreCase("DD")==0 || tfMes.getText().compareToIgnoreCase("MM")==0 || tfAnio.getText().compareToIgnoreCase("AAAA")==0){
            JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos");
        }
        else{
            try {
                try {
                    String SQL="call busquedaColonias(?)";
                    PreparedStatement pst= con.prepareStatement(SQL);
                    pst.setString(1, tfColonia.getText());
                    ResultSet res= pst.executeQuery();
                    if(res == null){
                        try {
                            SQL="call altaColonias(?)";
                            pst= con.prepareStatement(SQL);
                            pst.setString(1, tfColonia.getText());
                            pst.execute();

                        } catch (SQLException ex) {
                            Logger.getLogger(AltaVestidos.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error en la Colonia " + e.getMessage());
                }
                try {
                    String SQL="call altaClientes(?,?,?,?,?)";
                    PreparedStatement ppst= con.prepareStatement(SQL);
                    ppst.setString(1, tfNombres.getText());
                    ppst.setString(2, tfApellidos.getText());
                    ppst.setString(3, tfNumTel.getText());
                    int idCol;
                    String miniSQL="call getIdColonia(?)";
                    PreparedStatement pmst= con.prepareStatement(miniSQL);
                    pmst.setString(1, tfColonia.getText());
                    idCol= pmst.executeQuery().getInt(1);
                    ppst.setInt(4, idCol);
                    ppst.setString(5, tfNumTel.getText());
                    ppst.execute();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error en la alta " + e.getMessage());
                }

                if(getPrivileges()==1){
                    Empleados emp= new Empleados();
                    emp.setLayout(null);
                    emp.setLocationRelativeTo(null);
                    emp.setVisible(true);
                    this.setVisible(false);
                }
                else if(getPrivileges()==2){
                    Gerente ger = new Gerente();
                    ger.setLayout(null);
                    ger.setLocationRelativeTo(null);
                    ger.setVisible(true);
                    ger.setPrivileges(privileges);
                    this.setVisible(false);
            }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void tfColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfColoniaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        GestionClientes gesClien = new GestionClientes();
        gesClien.setLayout(null);
        gesClien.setLocationRelativeTo(null);
        gesClien.setVisible(true);
        gesClien.setPrivileges(privileges);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tfColoniaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfColoniaKeyReleased
        try {
            String SQL="call obtenerColonias(?)";
            PreparedStatement pst= con.prepareStatement(SQL);
            pst.setString(1, tfColonia.getText());
            ResultSet res= pst.executeQuery();
            
        } catch (Exception e) {

        }
    }//GEN-LAST:event_tfColoniaKeyReleased

    private void tfApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApellidosActionPerformed

    private void tfDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDiaActionPerformed

    private void tfMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMesActionPerformed

    private void tfAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnioActionPerformed

    private void tfNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombresKeyTyped

        int key = evt.getKeyChar();
        
        boolean mayusculas = key >= 65 && key <=90;

        boolean minusculas = key >= 97 && key <=122;

        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio))
    {
        evt.consume();
    }

    }//GEN-LAST:event_tfNombresKeyTyped

    private void tfApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfApellidosKeyTyped

        int key = evt.getKeyChar();
        
        boolean mayusculas = key >= 65 && key <=90;

        boolean minusculas = key >= 97 && key <=122;

        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio))
    {
        evt.consume();
    }

    }//GEN-LAST:event_tfApellidosKeyTyped

    private void tfNumTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNumTelKeyTyped
      
	int key = evt.getKeyChar();

        boolean numero = key >=8 && key <=57;

        if (!numero)
    {
	evt.consume();
    }  
    }//GEN-LAST:event_tfNumTelKeyTyped

    private void tfColoniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfColoniaKeyTyped

        int key = evt.getKeyChar();
        
        boolean mayusculas = key >= 65 && key <=90;

        boolean minusculas = key >= 97 && key <=122;

        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio))
    {
        evt.consume();
    }

    }//GEN-LAST:event_tfColoniaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroClientes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellidos;
    private javax.swing.JLabel CalleyNumero;
    private javax.swing.JLabel Colonia;
    private javax.swing.JLabel FechaNac;
    private javax.swing.JLabel Nombres;
    private javax.swing.JLabel NumTel;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel imgLogo3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField tfAnio;
    private javax.swing.JTextField tfApellidos;
    private javax.swing.JTextField tfCalleYNumero;
    private javax.swing.JTextField tfColonia;
    private javax.swing.JTextField tfDia;
    private javax.swing.JTextField tfMes;
    private javax.swing.JTextField tfNombres;
    private javax.swing.JTextField tfNumTel;
    // End of variables declaration//GEN-END:variables
}
